name: srijan's blog
markdown: redcarpet
pygments: true
baseurl: 
url: http://www.srijn.net
permalink: /:categories/:title.html
tag_title_prefix: "Tags &raquo; "
tag_dir: tag
related_tags: true
name: "srijan's Blog"
author: "Srijan Choudhary"
email: "srijan4@gmail.com"