name: "srijan's blog"
url: "https://www.srijn.net"
description: "The personal blog of Srijan Choudhary about programming, technology, linux"
author: "Srijan Choudhary"
email: "srijan4@gmail.com"
markdown: redcarpet
highlighter: pygments
baseurl: 
permalink: /:categories/:title.html
tag_title_prefix: "Tags &raquo; "
tag_dir: tag
related_tags: true
