baseurl = "https://www.srijn.net/"
languageCode = "en-us"
title = "srijan's blog"
theme = "crisp"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:filename"

[params]
  description = "Random posts on programming, linux, system administration, etc"
  author = "Srijan Choudhary"
  twitter = "srijan4"
  tag_domain = "www.srijn.net"
  creation_date = "2012-10-08"
  gplus = "111781135820248974565"
  ga = "UA-6428393-9"

[author]
  name = "Srijan Choudhary"
  email = "srijan4@gmail.com"
